### ISSUE TITLE
Error occurred in wordpress6.2.2

### ISSUE THREAD

**Issue by 963431755** [GBPrimepay/woocommerce-gbprimepay-checkout#1]
Fatal error: Uncaught Error: Class 'AS_Gbprimepay_API' not found in /home/www/wordpress/wp-content/plugins/woocommerce-gbprimepay-checkout-master/gbprimepay-payment-gateways.php:581 Stack trace: #0 /home/www/wordpress/wp-includes/class-wp-hook.php(308): AS_Gbprimepay->check_environment() #1 /home/www/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #2 /home/www/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /home/www/wordpress/wp-admin/admin.php(175): do_action() #4 /home/www/wordpress/wp-admin/about.php(10): require_once('/home/www/wordp...') #5 {main} thrown in /home/www/wordpress/wp-content/plugins/woocommerce-gbprimepay-checkout-master/gbprimepay-payment-gateways.php on line 581

**Comment by Ahz9619** [comment]
> Fatal: Uncaught : Class 'AS_Gbprimepay_API' not found in /home/www/wordpress/wp-content/plugins/woocommerce-gbprimepay-checkout-master/gbprimepay-payment-gateways.php:581 Stack trace: #10/home/www/wordpress/wp-includes/class-wp-hook.php(308): AS_Gbprimepay->check_environment() [#1](https://github.com/GBPrimepay/woocommerce-gbprimepay-checkout/issues/1) /home/www/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters() #2 /home/www/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action() #3 /home/www/wordpress/wp-admin/admin.php(175): do_action() #4 /home/www/wordpress/wp-admin/about.php(10): require_once('/home/www/wordp...') #5 {main} thrown in /home/www/wordpress/wp-content/plugins/woocommerce-gbprimepay-checkout-master/gbprimepay-payment-gateways.php on line 581
